import { invoke } from '@tauri-apps/api/core';
import { open, save } from '@tauri-apps/plugin-dialog';
import ReactECharts from 'echarts-for-react';
import { useMemo, useState } from 'react';
import './style.css';

type Row = Record<string, unknown>;
type View = 'build' | 'analysis' | 'settings';
type BuildTab = 'prepare' | 'import' | 'overview' | 'export';
type AnalysisTab = 'overview' | 'table' | 'visual' | 'metrics' | 'export';
type Lang = 'zh' | 'en';
type Overview = { source_count?: number; journal_count?: number; conference_count?: number; oa_count?: number; works_count?: number; cited_by_count?: number };

type Dict = typeof zh;
const zh = {
  brand:'OpenAlex Studio', sub:'学术影响力分析工作台', workspace:'工作区', build:'建库工作区', analysis:'分析工作区', settings:'设置', ready:'就绪', busy:'处理中', failed:'操作失败', chooseFirst:'请先选择路径。', connected:'已连接', imported:'建库完成', noData:'尚未连接数据源',
  buildTitle:'建库工作区', buildDesc:'准备 OpenAlex 数据，导入生成 Parquet / Arrow 数据库，并导出外部分析文件。', analysisTitle:'分析工作区', analysisDesc:'连接外部库或单个 Arrow / Parquet 文件，完成总览、表格检索、可视化和指标分析。',
  prepare:'准备数据', import:'导入建库', libraryOverview:'库概览', export:'导出', overview:'总览', table:'数据表', visual:'可视化', metrics:'指标分析',
  storageTitle:'数据布局', buildChecklist:'建库检查', raw:'原始 OpenAlex Sources 目录', output:'输出分析库目录', dataSource:'当前数据源', chooseDir:'选择目录', chooseFile:'选择文件', chooseLibrary:'选择库目录', connect:'连接', buildArrow:'生成 Arrow 快速读取布局', startBuild:'开始建库', openBuilt:'打开输出库',
  rawTip:'请选择包含 updated_date=*/part_0000.parquet 的 OpenAlex Sources 目录。', outTip:'输出目录将写入 manifest.json、parquet/sources.parquet 和 arrow/sources.arrow。', parquet:'Parquet：压缩、归档、打包和迁移', arrow:'Arrow：本地快速读取，面向零拷贝/mmap', manifest:'Manifest：记录逻辑 schema、物理文件和来源信息',
  sources:'Sources', journals:'期刊', conferences:'会议', oa:'OA 来源', works:'Works', cited:'总被引', type:'类型', journal:'期刊', conference:'会议', metric:'指标', keyword:'名称关键词', country:'国家代码', oaFilter:'OA 筛选', all:'全部', onlyOa:'仅 OA', onlyNonOa:'非 OA', run:'查询', ranking:'影响力排行', results:'结果表', exportRank:'导出排行', exportSearch:'导出检索', recent:'最近数据源', emptyRecent:'暂无最近连接',
  metricGuide:'指标解读', hTip:'H-index：稳健综合影响力，适合初筛和横向比较。', citedTip:'总被引：反映长期累积影响，但受出版年限和规模影响。', worksTip:'Works 数：反映产出规模，不等于质量。', i10Tip:'i10-index：至少被引 10 次的作品数量，反映稳定产出。', meanTip:'两年平均被引：更偏近期热度。', workflow:'学术工作流建议', w1:'先在总览确认数据源与规模，再进入数据表做精确筛选。', w2:'在可视化中观察 Top N 与异常值，最后导出结果用于论文、报告或 Excel 复核。', language:'界面语言', chinese:'中文', english:'English',
  metricOptions:[['h_index','H-index'],['cited_by_count','总被引'],['works_count','Works 数'],['i10_index','i10-index'],['mean_citedness_2yr','两年平均被引']]
};
const en: Dict = { ...zh, sub:'Scholarly impact analysis workbench', workspace:'Workspace', build:'Build Library', analysis:'Analysis', settings:'Settings', ready:'Ready', busy:'Working', failed:'Failed', chooseFirst:'Choose a path first.', connected:'Connected', imported:'Library built', noData:'No data source connected', buildTitle:'Build Library', buildDesc:'Prepare OpenAlex data, build Parquet / Arrow libraries, and export files for external analysis.', analysisTitle:'Analysis Workspace', analysisDesc:'Connect an external library or a single Arrow / Parquet file for overview, table search, visualization and metric analysis.', prepare:'Prepare', import:'Import', libraryOverview:'Library Overview', export:'Export', overview:'Overview', table:'Table', visual:'Visualize', metrics:'Metrics', raw:'Raw OpenAlex Sources folder', output:'Output analysis library folder', dataSource:'Current data source', chooseDir:'Choose folder', chooseFile:'Choose file', chooseLibrary:'Choose library', connect:'Connect', buildArrow:'Create Arrow fast-read layout', startBuild:'Build library', openBuilt:'Open output library', rawTip:'Choose a folder containing OpenAlex Sources partitions like updated_date=*/part_0000.parquet.', outTip:'The output folder will contain manifest.json, parquet/sources.parquet and arrow/sources.arrow.', parquet:'Parquet: compression, archive, package and transfer', arrow:'Arrow: fast local reads, zero-copy/mmap-oriented', manifest:'Manifest: logical schema, physical files and provenance', sources:'Sources', journals:'Journals', conferences:'Conferences', oa:'OA sources', works:'Works', cited:'Citations', type:'Type', journal:'Journal', conference:'Conference', metric:'Metric', keyword:'Name keyword', country:'Country code', oaFilter:'OA filter', all:'All', onlyOa:'OA only', onlyNonOa:'Non-OA', run:'Run', ranking:'Impact ranking', results:'Results table', exportRank:'Export ranking', exportSearch:'Export search', recent:'Recent sources', emptyRecent:'No recent source', metricGuide:'Metric guide', hTip:'H-index: robust overall impact for first-pass screening.', citedTip:'Citations: long-term accumulated impact, biased by age and size.', worksTip:'Works count: output scale, not quality.', i10Tip:'i10-index: number of works cited at least ten times.', meanTip:'2-year mean citedness: recent momentum.', workflow:'Research workflow tips', w1:'Check source and size in Overview first, then use Table for precise filtering.', w2:'Use Visualize to inspect Top N and outliers, then export to Excel or reports.', language:'Language', chinese:'中文', english:'English', metricOptions:[['h_index','H-index'],['cited_by_count','Cited by'],['works_count','Works'],['i10_index','i10-index'],['mean_citedness_2yr','2-year mean citedness']] };
const dict = { zh, en };

function rows(v: unknown): Row[] { return Array.isArray(v) ? v as Row[] : []; }
function first(v: unknown): Overview { return (Array.isArray(v) ? v[0] : v || {}) as Overview; }
function fmt(v: unknown) { return typeof v === 'number' ? Math.round(v).toLocaleString() : v == null || v === '' ? '—' : String(v); }
function short(p: string) { return !p ? '—' : p.length > 82 ? `…${p.slice(-79)}` : p; }
function loadRecent(): string[] { try { return JSON.parse(localStorage.getItem('recentSources') || '[]'); } catch { return []; } }
function remember(path: string) { const next = [path, ...loadRecent().filter(p => p !== path)].slice(0, 6); localStorage.setItem('recentSources', JSON.stringify(next)); return next; }
async function dir() { const v = await open({ directory:true, multiple:false }); return typeof v === 'string' ? v : ''; }
async function file() { const v = await open({ multiple:false, filters:[{ name:'OpenAlex data', extensions:['arrow','ipc','parquet'] }] }); return typeof v === 'string' ? v : ''; }

export default function App() {
  const [lang,setLang] = useState<Lang>((localStorage.getItem('lang') as Lang) === 'en' ? 'en' : 'zh');
  const t = dict[lang];
  const [view,setView] = useState<View>('build');
  const [buildTab,setBuildTab] = useState<BuildTab>('prepare');
  const [analysisTab,setAnalysisTab] = useState<AnalysisTab>('overview');
  const [busy,setBusy] = useState(false); const [status,setStatus] = useState('');
  const [rawDir,setRawDir] = useState(''); const [libraryDir,setLibraryDir] = useState(''); const [buildArrow,setBuildArrow] = useState(true);
  const [dataPath,setDataPath] = useState(''); const [recent,setRecent] = useState<string[]>(loadRecent());
  const [overview,setOverview] = useState<Overview|null>(null); const [ranking,setRanking] = useState<Row[]>([]); const [results,setResults] = useState<Row[]>([]);
  const [sourceType,setSourceType] = useState('journal'); const [metric,setMetric] = useState('h_index'); const [text,setText] = useState(''); const [country,setCountry] = useState(''); const [oaFilter,setOaFilter] = useState('all');
  const isOa = oaFilter === 'all' ? null : oaFilter === 'oa';
  const run = async (fn:()=>Promise<void>) => { setBusy(true); try { await fn(); } catch(e) { setStatus(`${t.failed}: ${e}`); } finally { setBusy(false); } };
  const refresh = async () => { setOverview(first(await invoke('dataset_overview'))); setRanking(rows(await invoke('top_sources',{metric,sourceType,limit:30}))); setResults(rows(await invoke('search_sources',{req:{text:text||null,sourceType,countryCode:country||null,isOa,limit:100,offset:0}}))); };
  const connect = async (path:string) => { if(!path){setStatus(t.chooseFirst);return;} await invoke('connect_dataset',{path}); setDataPath(path); setRecent(remember(path)); await refresh(); setStatus(`${t.connected}: ${path}`); setView('analysis'); setAnalysisTab('overview'); };
  const build = () => run(async()=>{ if(!rawDir || !libraryDir){setStatus(t.chooseFirst);return;} await invoke('import_sources',{req:{rawSourcesDir:rawDir,outputDir:libraryDir,buildArrowCache:buildArrow}}); setStatus(`${t.imported}: ${libraryDir}`); await connect(libraryDir); });
  const exportRows = (kind:'top'|'search') => run(async()=>{ const p = await save({ defaultPath: kind==='top'?'openalex-ranking.xlsx':'openalex-results.xlsx', filters:[{name:'CSV / Excel', extensions:['csv','xlsx']}] }); if(!p) return; if(kind==='top') await invoke('export_top_sources',{output:p,metric,sourceType,limit:1000}); else await invoke('export_search_sources',{output:p,req:{text:text||null,sourceType,countryCode:country||null,isOa,limit:1000,offset:0}}); setStatus(`${kind==='top'?t.exportRank:t.exportSearch}: ${p}`); });
  const chart = useMemo(()=>{ const top=ranking.slice(0,14).reverse(); return { grid:{left:180,right:24,top:16,bottom:26}, tooltip:{trigger:'axis'}, xAxis:{type:'value'}, yAxis:{type:'category',data:top.map(r=>r.display_name)}, series:[{type:'bar',barWidth:16,data:top.map(r=>r.metric_value),itemStyle:{color:'#6557f5',borderRadius:[0,6,6,0]}}]}; },[ranking]);
  const changeLang = (v:Lang) => { localStorage.setItem('lang',v); setLang(v); };

  const title = view==='build'?t.buildTitle:view==='analysis'?t.analysisTitle:t.settings;
  const desc = view==='build'?t.buildDesc:view==='analysis'?t.analysisDesc:t.language;
  return <div className="shell"><aside className="side"><div className="brand"><span>OA</span><div><b>{t.brand}</b><small>{t.sub}</small></div></div><em>{t.workspace}</em><Nav active={view==='build'} icon="▦" label={t.build} onClick={()=>setView('build')} /><Nav active={view==='analysis'} icon="⌕" label={t.analysis} onClick={()=>setView('analysis')} /><div className="sideBottom"><Nav active={view==='settings'} icon="⚙" label={t.settings} onClick={()=>setView('settings')} /><small>v0.1.0</small></div></aside><main className="main"><header className="head"><div><span className="crumb">OPENALEX / {view.toUpperCase()}</span><h1>{title}</h1><p>{desc}</p></div><div className={`pill ${busy?'busy':''}`}><i />{busy?t.busy:t.ready}</div></header>{status&&<div className="notice">{short(status)}</div>}{view==='build'&&<><TopTabs value={buildTab} setValue={setBuildTab} tabs={[[ 'prepare',t.prepare ],[ 'import',t.import ],[ 'overview',t.libraryOverview ],[ 'export',t.export ]]}/><BuildContent tab={buildTab} t={t} rawDir={rawDir} setRawDir={setRawDir} libraryDir={libraryDir} setLibraryDir={setLibraryDir} buildArrow={buildArrow} setBuildArrow={setBuildArrow} build={build} openBuilt={()=>run(()=>connect(libraryDir))} overview={overview} exportRows={exportRows} busy={busy}/></>}{view==='analysis'&&<><TopTabs value={analysisTab} setValue={setAnalysisTab} tabs={[[ 'overview',t.overview ],[ 'table',t.table ],[ 'visual',t.visual ],[ 'metrics',t.metrics ],[ 'export',t.export ]]}/><AnalysisContent tab={analysisTab} t={t} dataPath={dataPath} setDataPath={setDataPath} connect={()=>run(()=>connect(dataPath))} recent={recent} openRecent={(p:string)=>run(()=>connect(p))} overview={overview} sourceType={sourceType} setSourceType={setSourceType} metric={metric} setMetric={setMetric} text={text} setText={setText} country={country} setCountry={setCountry} oaFilter={oaFilter} setOaFilter={setOaFilter} refresh={()=>run(refresh)} ranking={ranking} results={results} chart={chart} exportRows={exportRows} busy={busy}/></>}{view==='settings'&&<Settings t={t} lang={lang} setLang={changeLang}/>}</main></div>;
}
function Nav(p:{active:boolean;icon:string;label:string;onClick:()=>void}){return <button className={`nav ${p.active?'active':''}`} onClick={p.onClick}><span>{p.icon}</span>{p.label}</button>}
function TopTabs<T extends string>({value,setValue,tabs}:{value:T;setValue:(v:T)=>void;tabs:string[][]}){return <div className="tabs">{tabs.map(([v,l])=><button key={v} className={value===v?'active':''} onClick={()=>setValue(v as T)}>{l}</button>)}</div>}
function BuildContent(p:any){const t:Dict=p.t; return <section className="page buildPage">{p.tab==='prepare'&&<><div className="card span2"><h2>{t.prepare}</h2><Path label={t.raw} value={p.rawDir} button={t.chooseDir} onPick={async()=>{const v=await dir(); if(v)p.setRawDir(v)}} disabled={p.busy}/><p>{t.rawTip}</p><Path label={t.output} value={p.libraryDir} button={t.chooseDir} onPick={async()=>{const v=await dir(); if(v)p.setLibraryDir(v)}} disabled={p.busy}/><p>{t.outTip}</p></div><LayoutCard t={t}/></>}{p.tab==='import'&&<><div className="card span2"><h2>{t.import}</h2><Path label={t.raw} value={p.rawDir} button={t.chooseDir} onPick={async()=>{const v=await dir(); if(v)p.setRawDir(v)}} disabled={p.busy}/><Path label={t.output} value={p.libraryDir} button={t.chooseDir} onPick={async()=>{const v=await dir(); if(v)p.setLibraryDir(v)}} disabled={p.busy}/><label className="toggle"><input type="checkbox" checked={p.buildArrow} onChange={(e)=>p.setBuildArrow(e.target.checked)}/>{t.buildArrow}</label><div className="actions"><button onClick={p.build} disabled={p.busy}>{t.startBuild}</button><button className="secondary" onClick={p.openBuilt} disabled={p.busy||!p.libraryDir}>{t.openBuilt}</button></div></div><Checklist t={t}/></>}{p.tab==='overview'&&<><Stats t={t} overview={p.overview}/><LayoutCard t={t}/></>}{p.tab==='export'&&<ExportCard t={t} exportRows={p.exportRows} disabled={!p.overview}/>}</section>}
function AnalysisContent(p:any){const t:Dict=p.t; const controls=<Controls t={t} {...p}/>; return <section className="page analysisPage">{p.tab==='overview'&&<><ConnectCard t={t} {...p}/><Stats t={t} overview={p.overview}/><div className="card"><h2>{t.workflow}</h2><p>{t.w1}</p><p>{t.w2}</p><Recent t={t} recent={p.recent} openRecent={p.openRecent}/></div></>}{p.tab==='table'&&<><ConnectCard t={t} {...p}/>{controls}<div className="card span3 tableCard"><Head title={t.results} action={<button className="textBtn" onClick={()=>p.exportRows('search')}>{t.exportSearch}</button>}/><DataTable rows={p.results.length?p.results:p.ranking}/></div></>}{p.tab==='visual'&&<><ConnectCard t={t} {...p}/>{controls}<div className="card span3 chartCard"><Head title={t.ranking} action={<button className="textBtn" onClick={()=>p.exportRows('top')}>{t.exportRank}</button>}/><ReactECharts option={p.chart} style={{height:'100%'}}/></div></>}{p.tab==='metrics'&&<><ConnectCard t={t} {...p}/><MetricGuide t={t}/></>}{p.tab==='export'&&<><ConnectCard t={t} {...p}/><ExportCard t={t} exportRows={p.exportRows} disabled={!p.overview}/></>}</section>}
function ConnectCard(p:any){const t:Dict=p.t;return <div className="card span3 compact"><h2>{t.dataSource}</h2><div className="sourceRow"><div className="path">{short(p.dataPath)}</div><button className="light" onClick={async()=>{const v=await dir();if(v)p.setDataPath(v)}} disabled={p.busy}>{t.chooseLibrary}</button><button className="light" onClick={async()=>{const v=await file();if(v)p.setDataPath(v)}} disabled={p.busy}>{t.chooseFile}</button><button onClick={p.connect} disabled={p.busy||!p.dataPath}>{t.connect}</button></div></div>}
function Controls(p:any){const t:Dict=p.t; return <div className="card span3 controls"><Sel label={t.type} value={p.sourceType} set={p.setSourceType} opts={[[ 'journal',t.journal ],[ 'conference',t.conference ]]}/><Sel label={t.metric} value={p.metric} set={p.setMetric} opts={t.metricOptions}/><Field label={t.keyword} value={p.text} set={p.setText} enter={p.refresh}/><Field label={t.country} value={p.country} set={(v)=>p.setCountry(v.toUpperCase())} enter={p.refresh}/><Sel label={t.oaFilter} value={p.oaFilter} set={p.setOaFilter} opts={[[ 'all',t.all ],[ 'oa',t.onlyOa ],[ 'non_oa',t.onlyNonOa ]]}/><button onClick={p.refresh} disabled={p.busy||!p.overview}>{t.run}</button></div>}
function Path(p:{label:string;value:string;button:string;onPick:()=>void;disabled:boolean}){return <div className="pathPick"><label>{p.label}</label><div><span>{short(p.value)}</span><button className="light" onClick={p.onPick} disabled={p.disabled}>{p.button}</button></div></div>}
function Stats({t,overview}:{t:Dict;overview:Overview|null}){return <div className="stats span2">{[[overview?.source_count,t.sources],[overview?.journal_count,t.journals],[overview?.conference_count,t.conferences],[overview?.oa_count,t.oa],[overview?.works_count,t.works],[overview?.cited_by_count,t.cited]].map(([v,l])=><div className="mini" key={String(l)}><span>{l}</span><b>{fmt(v)}</b></div>)}</div>}
function LayoutCard({t}:{t:Dict}){return <div className="card layout"><h2>{t.storageTitle}</h2><p>{t.parquet}</p><p>{t.arrow}</p><p>{t.manifest}</p></div>}
function Checklist({t}:{t:Dict}){return <div className="card"><h2>{t.buildChecklist}</h2><ul><li>{t.rawTip}</li><li>{t.outTip}</li><li>{t.arrow}</li></ul></div>}
function ExportCard(p:{t:Dict;exportRows:(k:'top'|'search')=>void;disabled:boolean}){return <div className="card span2"><h2>{p.t.export}</h2><p>{p.t.w2}</p><div className="actions"><button onClick={()=>p.exportRows('top')} disabled={p.disabled}>{p.t.exportRank}</button><button className="secondary" onClick={()=>p.exportRows('search')} disabled={p.disabled}>{p.t.exportSearch}</button></div></div>}
function MetricGuide({t}:{t:Dict}){return <div className="card span3 metricGrid"><h2>{t.metricGuide}</h2>{[t.hTip,t.citedTip,t.worksTip,t.i10Tip,t.meanTip].map((x,i)=><p key={i}>{x}</p>)}</div>}
function Recent({t,recent,openRecent}:{t:Dict;recent:string[];openRecent:(p:string)=>void}){return <div className="recent"><h3>{t.recent}</h3>{recent.length?recent.map(r=><button key={r} onClick={()=>openRecent(r)}>{short(r)}</button>):<small>{t.emptyRecent}</small>}</div>}
function Head({title,action}:{title:string;action:React.ReactNode}){return <div className="cardHead"><h2>{title}</h2>{action}</div>}
function Sel(p:{label:string;value:string;set:(v:string)=>void;opts:string[][]}){return <label className="field"><span>{p.label}</span><select value={p.value} onChange={e=>p.set(e.target.value)}>{p.opts.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label>}
function Field(p:{label:string;value:string;set:(v:string)=>void;enter:()=>void}){return <label className="field"><span>{p.label}</span><input value={p.value} onChange={e=>p.set(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')p.enter()}}/></label>}
function DataTable({rows}:{rows:Row[]}){const cols=['display_name','source_type','country_code','h_index','i10_index','cited_by_count','works_count','mean_citedness_2yr'];return <div className="tableWrap"><table><thead><tr>{cols.map(c=><th key={c}>{c}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={String(r.openalex_id??i)}>{cols.map(c=><td key={c}>{fmt(r[c])}</td>)}</tr>)}</tbody></table></div>}
function Settings({t,lang,setLang}:{t:Dict;lang:Lang;setLang:(v:Lang)=>void}){return <section className="page"><div className="card span2"><h2>{t.language}</h2><button className={lang==='zh'?'selected secondary':'secondary'} onClick={()=>setLang('zh')}>{t.chinese}</button><button className={lang==='en'?'selected secondary':'secondary'} onClick={()=>setLang('en')}>{t.english}</button></div><LayoutCard t={t}/></section>}

