[package]
name = "cistella-tree-space"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
name = "cistella_tree_space"
path = "src/lib.rs"

[dependencies]
arrow.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
tree-space = { path = "../tree-space/tree-space" }
